### ISSUE TITLE
Create a subdomain arbitrator.kleros.io rather than multiplying TLDs

### ISSUE THREAD

**Issue by marsrobertson** [kleros/centralized-arbitrator-integration-demo#19]
* https://centralizedarbitrator.fyi
* https://dogesontrial.dog

10 years from now - who will be managing the domains? SSL certificates? Certificate pinning? MITM attack? Typosquatting?

NOPE.

I trust https://kleros.io

**Comment by marsrobertson** [comment]
Is the domain online right now?

https://centralizedarbitrator.fyi/

https://downforeveryoneorjustme.com/centralizedarbitrator.fyi

![image](https://user-images.githubusercontent.com/44369284/72755842-63f6c680-3bc3-11ea-8f4d-43115c11904b.png)

**Comment by 0xferit** [comment]
Now it's https://centralizedarbitrator.kleros.io.
