### ISSUE TITLE
Provide an easy way to verify contract source on Etherscan (maybe even use their API)

### ISSUE THREAD

**Issue by marsrobertson** [kleros/centralized-arbitrator-integration-demo#22]
This is the one I've deployed: https://kovan.etherscan.io/address/0x94a796d6d5b4ff7f622fc10f893a64c9a802e84f#code
![image](https://user-images.githubusercontent.com/44369284/56658798-71fad380-6693-11e9-9948-0c4917cdcc3c.png)

I was hoping that at least the first one has source code verified.

The bytecode comes from another repository, from a folder that is `.gitignore` but at least we know where to look for it: https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/CentralizedArbitrator.sol

https://github.com/kleros/centralized-arbitrator-dashboard/blob/c7eca052d36322d30effd5866b1045d6962daa77/src/ethereum/auto-appealable-arbitrator.js#L1-L10

**Comment by 0xferit** [comment]
Yeah, this would be really handy. @marsrobertson

**Comment by 0xferit** [comment]
Now every contract deployed will be verified.
