### ISSUE TITLE
Evidence not shown

### ISSUE THREAD

**Issue by sneaker1** [kleros/centralized-arbitrator-integration-demo#27]
Hello,

the provided evidence is not shown on the dashboard. Is this not implemented or am I doing something wrong?
Please take a look at the screenshot. 
In the console output i can see that the evidence event with the Evidence JSON seems to be read correcty by the dashboard. 

![Browser_Console](https://user-images.githubusercontent.com/84079326/119971011-bbbff180-bfb0-11eb-9339-f7a7b0a71dd1.png)

In the metaevidence JSON i have NOT used the evidenceDisplayInterfaceURL. 
But i would guess it should fallback to a default one.

Network: Kovan
Centralized Arbitrator Contract: 0x42c6d4b8Cd4363c02d491CEe0Daa9A6292e3be1C
Arbitrable Contract: 0x959d33f7d0647A7FB54c3C9086CE58F9b72bA201

Regards
Sneaker

**Comment by 0xferit** [comment]
Hello, @sneaker1 thanks for reporting. Might be a bug, I'm going to investigate. Meanwhile, if you manage to see evidence, please let me know.

**Comment by 0xferit** [comment]
I think I found the problem: App expects aliases in metaevidence (it assumes a binary dispute and aliases defined, at the time this application was built Kleros was not supporting anything except binary disputes so it made sense at the time). I can fix it in few days, meanwhile, you can wait until it's fixed or you can provide aliases in metaevidence.

**Comment by 0xferit** [comment]
@sneaker1 Fixed the problem, you should be able to see evidence now. Feel free to reopen if the issue persists.
